### ISSUE TITLE
KiCost - No Farnell results

### ISSUE THREAD

**Issue by iahim67** [hildogjr/KiCost#245]
I have created a KiCad 4.07 schematics and used Farnell components (manf# new field).
Seems that KiCost is able to get the parts in my BOM from all distributors except Farnell.
I have installed and used both 0.1.43 and beta KiCost from github (https://github.com/xesscorp/KiCost) with same results. I tried resistors, diodes, capacitors, connectors from Farnell but there are always 0 results from Farnell while there are more or less results from the rest of the distributors.
![image](https://user-images.githubusercontent.com/38937665/39565573-24edc5c4-4ec1-11e8-9d0b-6a8a35e6c332.png)

[tutorial1.xlsx](https://github.com/xesscorp/KiCost/files/1970029/tutorial1.xlsx)

[tutorial1.zip](https://github.com/xesscorp/KiCost/files/1970031/tutorial1.zip)

#### Issue / Problem report
Add:
1. Terminal error report / txt;
2. Use ``--debug`` option on KiCost call;
2. Write the command used to call KiCost (or the graphical interface configuration);
3. One BoM to reproduce the error (with the EDA version).

#### Feature / Enhancement request
- Explain it will help the other users.

The team thanks your contribution.

**Comment by xesscorp** [comment]
This happens because Farnell returns a page with Javascript to redirect to the product page that kicost has requested. Kicost can't execute the Javascript or find the link to the page, so no part information can be scraped. The only solution to this may be to use a Python package like Selenium and mimic the operation of an actual browser. Without doing that, kicost will not be able to scrape Farnell.

**Comment by hildogjr** [comment]
A little more complicated that I was thinking. I just check the HTML tags and appear fine.
May be related with #242?

**Comment by iahim67** [comment]
Does it mean there is no solution in the near future for Farnell?

**Comment by hildogjr** [comment]
Sure there is, but for now @xesscorp can help quick than I (maybe as he said, using some aditional Python package to scrape or emulate the browser).
I have to study a little, javascript and its interaction in the web is not my strong.

**Comment by iahim67** [comment]
OK, thank's for now  :-)

**Comment by hildogjr** [comment]
Now, with #223 enhancement will be more simple to do this improvement to all distributors submodules (also fixing probable #242). The fix of this issue can be written on `fake_browser()` to reach all the distributors.
We have to find a good package little and of good maintenance (Selenium, in first analyze appear heavy and full of features that we don't need).

**Comment by hildogjr** [comment]
Checking the documentation about `selenium` is needed some thirty browser / actual browser plugin (in the case of Firefox / Chrome) plus (in my tests) a configuration of the installed browser folder (that change in each OS).
These leave me concerned.

Some option to be tested: https://www.youtube.com/watch?v=FSH77vnOGqU

**Comment by mmmaisel** [comment]
I did some experiments in an empty browser session and it seems that the root cause of this is missing cookies as in issue #242.

Additionally, the Farnell search URL has changed from `http://it.farnell.com/webapp/wcs/stores/servlet/Search?catalogId=15001&langId=-4&storeId=10165&gs=true&st=` to `http://it.farnell.com/Search?storeId=10165&catalogId=15001&categoryName=&selectedCategoryId=&langId=-4&categoryIdBox=&st=`.

Steps to reproduce my test:
* Clear all browser cookies
* Access KiCost's search URL with a part number -> get javascript redirect
* Clear cookies again, then access `it.farnell.com` main site
* Access KiCost's search URL with a part number -> it works

So fixing #242 should fix this as well, no need to implement javascript.
