### ISSUE TITLE
Multiple options for MPNs?

### ISSUE THREAD

**Issue by adamwolf** [hildogjr/KiCost#383]
Hi folks!  Is there a way to put multiple equivalent part numbers in a BOM and have KiCost look at all of them and pick the lowest cost option?

**Comment by hildogjr** [comment]
Multple: yes. Look for "multiple/sub-parts" into the manual page https://xesscorp.github.io/KiCost/docs/_build/singlehtml/index.html
Lowest cost, you will have to choose manually at the spreadsheet.

Because it is a doubt, this thread will be closed. Fell free to reopen.
This feature was ask some time ago but I have had no time to work in.
