### ISSUE TITLE
Ignore Value when grouping

### ISSUE THREAD

**Issue by metropt** [hildogjr/KiCost#389]
How can I group the following parts by footprint and manf# per example?

I tried to use the --group_fields for value but it stopped with an error.

![image](https://user-images.githubusercontent.com/764040/76079663-08c73a80-5f9d-11ea-9fc3-ae67bf9f2176.png)

Thank you

**Comment by hildogjr** [comment]
I think it not possible, did you get some warning message?
By safety I believe the is not possible to merge different value parts, because they are essentially different component electrical parts.
I have the same use of your and I use the `Desc` field at KiCost (or other EDA) to tell the button function (`kicost foo --group_fields desc`). The values of all them stay as "micro switch" or something like that.

**Comment by metropt** [comment]
I'll do that. Will start Desc for this kind of information.

**Comment by hildogjr** [comment]
"desc" and "description" are deal as alias by KiCost.
You can also run `kicost --setup` (update your version to the last one available here) to create all the configurations and default fields in KiCad. This operation should be automatically done on installation but #372.
